AWSTemplateFormatVersion: 2010-09-09
Description: Common-TransitGatewayAttachment Template.
  This template creates a TransitGatewayAttachment.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - VPCStackName
          - TransitGatewayStackName
      - Label:
          default: System Configuration
        Parameters:
          - CompanyName
          - SystemName
      - Label:
          default: Environment Configuration
        Parameters:
          - AccountName
          - EnvironmentName
    ParameterLabels:
      VPCStackName:
        default: VPC Stack Name
      TransitGatewayStackName:
        default: TransitGateway Stack Name
      CompanyName:
        default: Company Name
      SystemName:
        default: System Name
      AccountName:
        default: Account Name
      EnvironmentName:
        default: Environment Name
Parameters:
  VPCStackName:
    Description: Name of the CloudFormation Stack containing the VPC
    Type: String
    MinLength: 6
    MaxLength: 64
    Default: Production-VPC
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  TransitGatewayStackName:
    Description: Name of the CloudFormation Stack containing the TransitGateway
    Type: String
    MinLength: 6
    MaxLength: 64
    Default: Production-TransitGateway
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  CompanyName:
    Description: Name of the Company associated with the Stack
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: Camelz
    AllowedPattern: ^[A-Z][a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  SystemName:
    Description: Name of the System associated with the Stack
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: Prototype
    AllowedPattern: ^[A-Z][a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  AccountName:
    Description: Name of the Account associated with the Stack
    Type: String
    Default: Core
    AllowedValues:
      - Build
      - Core
      - Jumpstart
    ConstraintDescription: must be Core or Jumpstart.
  EnvironmentName:
    Description: Name of the Environment associated with the Stack
    Type: String
    Default: Core
    AllowedValues:
      - Build
      - Core
    ConstraintDescription: must be Core (may expand later).
Resources:
  TransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      VpcId: !ImportValue
        Fn::Sub: ${VPCStackName}-VPC
      TransitGatewayId: !ImportValue
        Fn::Sub: ${TransitGatewayStackName}-TransitGateway
      SubnetIds:
        - !ImportValue
          Fn::Sub: ${VPCStackName}-PublicSubnetA
        - !ImportValue
          Fn::Sub: ${VPCStackName}-PublicSubnetB
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-TransitGatewayAttachment
  TransitGatewayRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      TransitGatewayId: !ImportValue
        Fn::Sub: ${TransitGatewayStackName}-TransitGateway
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-TransitGatewayRouteTable
  TransitGatewayRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachment
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable
  TransitGatewayRouteTablePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachment
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable
Outputs:
  TransitGatewayAttachment:
    Description: The TransitGatewayAttachment
    Value: !Ref TransitGatewayAttachment
    Export:
      Name: !Sub ${AWS::StackName}-TransitGatewayAttachment
