AWSTemplateFormatVersion: 2010-09-09
Description: Common-TransitGateway Template.
  This template creates a TransitGateway.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - ReferenceFunctionsStackName
      - Label:
          default: System Configuration
        Parameters:
          - CompanyName
          - SystemName
      - Label:
          default: Environment Configuration
        Parameters:
          - AccountName
          - EnvironmentName
      - Label:
          default: TransitGateway Configuration
        Parameters:
          - TransitGatewayAccount
          - TransitGatewayASN
          - AutoAcceptSharedAttachments
          - DnsSupport
          - VpnEcmpSupport
      - Label:
          default: ResourceShare Configuration
        Parameters:
          - TransitGatewayResourceShareName
          - Organization
          - AllowExternalPrincipals
      - Label:
          default: Account Dependencies
        Parameters:
          - OrganizationAccount
          - JumpstartAccount
          - ManagementAccount
          - LogAccount
          - RecoveryAccount
          - BuildAccount
          - CoreAccount
          - ProductionAccount
          - StagingAccount
          - UATAccount
          - QAAccount
          - TestingAccount
          - DevelopmentAccount
    ParameterLabels:
      ReferenceFunctionsStackName:
        default: ReferenceFunctions Stack Name
      CompanyName:
        default: Company Name
      SystemName:
        default: System Name
      AccountName:
        default: Account Name
      EnvironmentName:
        default: Environment Name
      TransitGatewayAccount:
        default: TransitGateway Account
      TransitGatewayASN:
        default: TransitGateway ASN
      AutoAcceptSharedAttachments:
        default: Auto-Accept Shared Attachments
      DnsSupport:
        default: DNS Support
      VpnEcmpSupport:
        default: VPN ECMP Support
      TransitGatewayResourceShareName:
        default: TransitGateway ResourceShare Name
      Organization:
        default: Organization
      AllowExternalPrincipals:
        default: Allow External Principals
      OrganizationAccount:
        default: Organization Account
      JumpstartAccount:
        default: Jumpstart Account
      ManagementAccount:
        default: Management Account
      LogAccount:
        default: Log Account
      RecoveryAccount:
        default: Recovery Account
      BuildAccount:
        default: Build Account
      CoreAccount:
        default: Core Account
      ProductionAccount:
        default: Production Account
      StagingAccount:
        default: Staging Account
      UATAccount:
        default: UAT Account
      QAAccount:
        default: QA Account
      TestingAccount:
        default: Testing Account
      DevelopmentAccount:
        default: Development Account
Parameters:
  ReferenceFunctionsStackName:
    Description: Name of the CloudFormation Stack containing the Reference Functions
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: ReferenceFunctions
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  CompanyName:
    Description: Name of the Company associated with the Stack
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: Camelz
    AllowedPattern: ^[A-Z][a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  SystemName:
    Description: Name of the System associated with the Stack
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: Prototype
    AllowedPattern: ^[A-Z][a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  AccountName:
    Description: Name of the Account associated with the Stack
    Type: String
    Default: Core
    AllowedValues:
      - Build
      - Core
      - Jumpstart
    ConstraintDescription: must be Core or Jumpstart.
  EnvironmentName:
    Description: Name of the Environment associated with the Stack
    Type: String
    Default: Core
    AllowedValues:
      - Build
      - Core
    ConstraintDescription: must be Core (may expand later).
  TransitGatewayAccount:
    Description: AWS Account ID of the Account where TransitGateway should be created.
      All other accounts will attempt to share the TransitGateway created in this Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  TransitGatewayASN:
    Description: Autonomous System Number for the TransitGateway
    Type: Number
    Default: 64512
    MinValue: 64512
    MaxValue: 65534
    ConstraintDescription: must be an integer between 64512 and 65534.
  AutoAcceptSharedAttachments:
    Description: Automatically accept attachment requests
    Type: String
    Default: enable
    AllowedValues:
      - enable
      - disable
    ConstraintDescription: must be either enable or disable.
  DnsSupport:
    Description: Support DNS
    Type: String
    Default: enable
    AllowedValues:
      - enable
      - disable
    ConstraintDescription: must be either enable or disable.
  VpnEcmpSupport:
    Description: Support Equal Cost Multipath Protocol on VPN Connections
    Type: String
    Default: enable
    AllowedValues:
      - enable
      - disable
    ConstraintDescription: must be either enable or disable.
  TransitGatewayResourceShareName:
    Description: Name of the ResourceShare associated with the shared TransitGateway created in another Account
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Core-TransitGatewayResourceShare
    AllowedPattern: ^(Organization|Management|Production|Core)-TransitGatewayResourceShare$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  Organization:
    Description: AWS Organization ID
    Type: String
    Default: ''
    AllowedPattern: (^$|^o-[0-9][a-z]{10}$)
    ConstraintDescription: must be a valid AWS Organization ID, or blank.
  AllowExternalPrincipals:
    Description: Allow External Principals (Specifying any Account will force this to true)
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: must be either true or false.
  OrganizationAccount:
    Description: AWS Account ID of the Organization Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  JumpstartAccount:
    Description: AWS Account ID of the Jumpstart Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  ManagementAccount:
    Description: AWS Account ID of the Management Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  LogAccount:
    Description: AWS Account ID of the Log Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  RecoveryAccount:
    Description: AWS Account ID of the Recovery Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  BuildAccount:
    Description: AWS Account ID of the Build Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  CoreAccount:
    Description: AWS Account ID of the Core Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  ProductionAccount:
    Description: AWS Account ID of the Production Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  StagingAccount:
    Description: AWS Account ID of the Staging Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  UATAccount:
    Description: AWS Account ID of the UAT Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  QAAccount:
    Description: AWS Account ID of the QA Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  TestingAccount:
    Description: AWS Account ID of the Testing Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
  DevelopmentAccount:
    Description: AWS Account ID of the Development Account
    Type: String
    Default: ''
    AllowedPattern: (^$|^[0-9]{12}$)
    ConstraintDescription: must be a valid AWS Account ID, or blank.
Conditions:
  CreateTransitGateway: !Or [ !Equals [ !Ref TransitGatewayAccount, '' ],
                              !Equals [ !Ref TransitGatewayAccount, 'AWS::AccountId' ]]
  ShareTransitGateway: !Not [ !Condition CreateTransitGateway ]
  ConfigureOrganization: !Not [ !Equals [ !Ref Organization, '' ]]
  ConfigureOrganizationAccount: !And [ !Not [ !Equals [ !Ref OrganizationAccount, '' ]],
                                       !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureJumpstartAccount: !And [ !Not [ !Equals [ !Ref JumpstartAccount, '' ]],
                                    !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureManagementAccount: !And [ !Not [ !Equals [ !Ref ManagementAccount, '' ]],
                                     !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureLogAccount: !And [ !Not [ !Equals [ !Ref LogAccount, '' ]],
                              !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureRecoveryAccount: !And [ !Not [ !Equals [ !Ref RecoveryAccount, '' ]],
                                   !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureBuildAccount: !And [ !Not [ !Equals [ !Ref BuildAccount, '' ]],
                                !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureCoreAccount: !And [ !Not [ !Equals [ !Ref CoreAccount, '' ]],
                               !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureProductionAccount: !And [ !Not [ !Equals [ !Ref ProductionAccount, '' ]],
                                     !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureStagingAccount: !And [ !Not [ !Equals [ !Ref StagingAccount, '' ]],
                                  !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureUATAccount: !And [ !Not [ !Equals [ !Ref UATAccount, '' ]],
                              !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureQAAccount: !And [ !Not [ !Equals [ !Ref QAAccount, '' ]],
                             !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureTestingAccount: !And [ !Not [ !Equals [ !Ref TestingAccount, '' ]],
                                  !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureDevelopmentAccount: !And [ !Not [ !Equals [ !Ref DevelopmentAccount, '' ]],
                                      !Not [ !Equals [ !Ref CoreAccount, 'AWS::AccountId' ]]]
  ConfigureExternalAccounts: !Or [ !Not [ !Condition ConfigureOrganization ],
                                   !Or [ !Condition ConfigureOrganizationAccount,
                                         !Condition ConfigureJumpstartAccount,
                                         !Condition ConfigureManagementAccount,
                                         !Condition ConfigureLogAccount,
                                         !Condition ConfigureRecoveryAccount,
                                         !Condition ConfigureBuildAccount,
                                         !Condition ConfigureCoreAccount ],
                                   !Or [ !Condition ConfigureProductionAccount,
                                         !Condition ConfigureUATAccount,
                                         !Condition ConfigureQAAccount,
                                         !Condition ConfigureTestingAccount,
                                         !Condition ConfigureDevelopmentAccount ]]
Resources:
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      Description: !Sub ${EnvironmentName}-TransitGateway
      AmazonSideAsn: !Ref TransitGatewayASN
      AutoAcceptSharedAttachments: !Ref AutoAcceptSharedAttachments
      DefaultRouteTableAssociation: disable
      DefaultRouteTablePropagation: disable
      DnsSupport: !Ref DnsSupport
      VpnEcmpSupport: !Ref VpnEcmpSupport
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-TransitGateway
    Condition: CreateTransitGateway
  TransitGatewayResourceShare:
    Type: AWS::RAM::ResourceShare
    Properties:
      Name: !Ref TransitGatewayResourceShareName
      AllowExternalPrincipals: !If [ ConfigureExternalAccounts, true, !Ref AllowExternalPrincipals ]
      ResourceArns:
        - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:transit-gateway/${TransitGateway}
      Principals:
        - !If [ ConfigureOrganization, !Ref Organization, !Ref 'AWS::NoValue' ]
        - !If [ ConfigureOrganizationAccount, !Ref OrganizationAccount, !Ref 'AWS::NoValue' ]
        - !If [ ConfigureJumpstartAccount, !Ref JumpstartAccount, !Ref 'AWS::NoValue' ]
        - !If [ ConfigureLogAccount, !Ref LogAccount, !Ref 'AWS::NoValue' ]
        - !If [ ConfigureRecoveryAccount, !Ref RecoveryAccount, !Ref 'AWS::NoValue' ]
        - !If [ ConfigureBuildAccount, !Ref BuildAccount, !Ref 'AWS::NoValue' ]
        - !If [ ConfigureCoreAccount, !Ref CoreAccount, !Ref 'AWS::NoValue' ]
        - !If [ ConfigureProductionAccount, !Ref ProductionAccount, !Ref 'AWS::NoValue' ]
        - !If [ ConfigureStagingAccount, !Ref StagingAccount, !Ref 'AWS::NoValue' ]
        - !If [ ConfigureUATAccount, !Ref UATAccount, !Ref 'AWS::NoValue' ]
        - !If [ ConfigureTestingAccount, !Ref TestingAccount, !Ref 'AWS::NoValue' ]
        - !If [ ConfigureDevelopmentAccount, !Ref DevelopmentAccount, !Ref 'AWS::NoValue' ]
      Tags:
       - Key: Name
         Value: !Sub ${EnvironmentName}-TransitGatewayResourceShare
    Condition: CreateTransitGateway
  TransitGatewayReference:
    Type: Custom::TransitGatewayReference
    Properties:
      ServiceToken: !ImportValue
        Fn::Sub: ${ReferenceFunctionsStackName}-TransitGatewayReferenceFunctionArn
      ResourceShareName: !Ref TransitGatewayResourceShareName
      SenderAccountId: !Ref TransitGatewayAccount
    Condition: ShareTransitGateway
Outputs:
  TransitGateway:
    Description: The TransitGateway
    Value: !If [ CreateTransitGateway, !Ref TransitGateway, !Ref TransitGatewayReference ]
    Export:
      Name: !Sub ${AWS::StackName}-TransitGateway
