AWSTemplateFormatVersion: 2010-09-09
Description: Environment-VPC-CidrTest Template.
  This creates an Environment VPC using a CIDR which must match EnvironmentType restrictions. Multiple Environment VPCs can co-exist. The VPC is always Multi-Zone. It can optionally be Multi-NAT Gateway.
Parameters:
  EnvironmentType:
    Description: Type of the Environment to build. Used to select size-related options in Mappings
    Type: String
    Default: small
    AllowedValues:
      - small
      - medium
      - large
      - xlarge
      - 2xlarge
    ConstraintDescription: must be small, medium, large, xlarge or 2xlarge.
  Network:
    Description: VPC Network
    Type: String
    Default: 10.160.64.0/20
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/(1[8-9]|2[0-2])$
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/18-22.
Mappings:
  NetworkCalculationMap:
    CidrBits:
      small: 4
      medium: 5
      large: 6
      xlarge: 7
      2xlarge: 8
    CidrCount:
      small: 16
      medium: 32
      large: 64
      xlarge: 128
      2xlarge: 256
    AZAOffset:
      small: 3
      medium: 7
      large: 15
      xlarge: 31
      2xlarge: 63
    AZBOffset:
      small: 7
      medium: 15
      large: 31
      xlarge: 63
      2xlarge: 127
    AZCOffset:
      small: 11
      medium: 23
      large: 47
      xlarge: 95
      2xlarge: 191
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Ref Network
      Tags:
        - Key: Name
          Value: Dummy-VPC
Outputs:
  VPC:
    Description: The VPC
    Value: !Ref VPC
  VPCCidr:
    Description: The CIDR of the VPC
    Value: !GetAtt VPC.CidrBlock
  PublicSubnetACidr:
    Description: The CIDR of the Public Subnet in Availability Zone A
    Value: !Select [ 0, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  PublicSubnetBCidr:
    Description: The CIDR of the Public Subnet in Availability Zone B
    Value: !Select [ 16, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  PublicSubnetCCidr:
    Description: The CIDR of the Public Subnet in Availability Zone C
    Value: !Select [ 32, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  Public1SubnetACidr:
    Description: The CIDR of the Public1 Subnet in Availability Zone A
    Value: !Select [ 1, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  Public1SubnetBCidr:
    Description: The CIDR of the Public1 Subnet in Availability Zone B
    Value: !Select [ 17, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  Public1SubnetCCidr:
    Description: The CIDR of the Public1 Subnet in Availability Zone C
    Value: !Select [ 33, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  WebSubnetACidr:
    Description: The CIDR of the Web Subnet in Availability Zone A
    Value: !Select [ 2, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]] ]
  WebSubnetBCidr:
    Description: The CIDR of the Web Subnet in Availability Zone B
    Value: !Select [ 18, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  WebSubnetCCidr:
    Description: The CIDR of the Web Subnet in Availability Zone C
    Value: !Select [ 34, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  Web1SubnetACidr:
    Description: The CIDR of the Web1 Subnet in Availability Zone A
    Value: !Select [ 3, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]] ]
  Web1SubnetBCidr:
    Description: The CIDR of the Web1 Subnet in Availability Zone B
    Value: !Select [ 19, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  Web1SubnetCCidr:
    Description: The CIDR of the Web1 Subnet in Availability Zone C
    Value: !Select [ 35, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  ApplicationSubnetACidr:
    Description: The CIDR of the Application Subnet in Availability Zone A
    Value: !Select [ 4, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]] ]
  ApplicationSubnetBCidr:
    Description: The CIDR of the Application Subnet in Availability Zone B
    Value: !Select [ 20, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  ApplicationSubnetCCidr:
    Description: The CIDR of the Application Subnet in Availability Zone C
    Value: !Select [ 36, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  Application1SubnetACidr:
    Description: The CIDR of the Application1 Subnet in Availability Zone A
    Value: !Select [ 5, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]] ]
  Application1SubnetBCidr:
    Description: The CIDR of the Application1 Subnet in Availability Zone B
    Value: !Select [ 21, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  Application1SubnetCCidr:
    Description: The CIDR of the Application1 Subnet in Availability Zone C
    Value: !Select [ 37, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  DatabaseSubnetACidr:
    Description: The CIDR of the Database Subnet in Availability Zone A
    Value: !Select [ 8, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]] ]
  DatabaseSubnetBCidr:
    Description: The CIDR of the Database Subnet in Availability Zone B
    Value: !Select [ 24, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  DatabaseSubnetCCidr:
    Description: The CIDR of the Database Subnet in Availability Zone C
    Value: !Select [ 40, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  Database1SubnetACidr:
    Description: The CIDR of the Database1 Subnet in Availability Zone A
    Value: !Select [ 9, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]] ]
  Database1SubnetBCidr:
    Description: The CIDR of the Database1 Subnet in Availability Zone B
    Value: !Select [ 25, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  Database1SubnetCCidr:
    Description: The CIDR of the Database1 Subnet in Availability Zone C
    Value: !Select [ 41, !Cidr [ !GetAtt VPC.CidrBlock, 64, !FindInMap [ NetworkCalculationMap, CidrBits, !Ref EnvironmentType ]]]
  IdentitySubnetACidr:
    Description: The CIDR of the Identity Subnet in Availability Zone A
    Value: !Select [ 2, !Cidr [ !Select [ !FindInMap [ NetworkCalculationMap, AZAOffset, !Ref EnvironmentType ], !Cidr [ !GetAtt VPC.CidrBlock, !FindInMap [ NetworkCalculationMap, CidrCount, !Ref EnvironmentType ], 6 ] ], 4, 4 ] ]
  IdentitySubnetBCidr:
    Description: The CIDR of the Identity Subnet in Availability Zone B
    Value: !Select [ 2, !Cidr [ !Select [ !FindInMap [ NetworkCalculationMap, AZBOffset, !Ref EnvironmentType ], !Cidr [ !GetAtt VPC.CidrBlock, !FindInMap [ NetworkCalculationMap, CidrCount, !Ref EnvironmentType ], 6 ] ], 4, 4 ] ]
  IdentitySubnetCCidr:
    Description: The CIDR of the Identity Subnet in Availability Zone C
    Value: !Select [ 2, !Cidr [ !Select [ !FindInMap [ NetworkCalculationMap, AZCOffset, !Ref EnvironmentType ], !Cidr [ !GetAtt VPC.CidrBlock, !FindInMap [ NetworkCalculationMap, CidrCount, !Ref EnvironmentType ], 6 ] ], 4, 4 ] ]
  NetworkSubnetACidr:
    Description: The CIDR of the Network Subnet in Availability Zone A
    Value: !Select [ 3, !Cidr [ !Select [ !FindInMap [ NetworkCalculationMap, AZAOffset, !Ref EnvironmentType ], !Cidr [ !GetAtt VPC.CidrBlock, !FindInMap [ NetworkCalculationMap, CidrCount, !Ref EnvironmentType ], 6 ] ], 4, 4 ] ]
  NetworkSubnetBCidr:
    Description: The CIDR of the Network Subnet in Availability Zone B
    Value: !Select [ 3, !Cidr [ !Select [ !FindInMap [ NetworkCalculationMap, AZBOffset, !Ref EnvironmentType ], !Cidr [ !GetAtt VPC.CidrBlock, !FindInMap [ NetworkCalculationMap, CidrCount, !Ref EnvironmentType ], 6 ] ], 4, 4 ] ]
  NetworkSubnetCCidr:
    Description: The CIDR of the Network Subnet in Availability Zone C
    Value: !Select [ 3, !Cidr [ !Select [ !FindInMap [ NetworkCalculationMap, AZCOffset, !Ref EnvironmentType ], !Cidr [ !GetAtt VPC.CidrBlock, !FindInMap [ NetworkCalculationMap, CidrCount, !Ref EnvironmentType ], 6 ] ], 4, 4 ] ]
