AWSTemplateFormatVersion: 2010-09-09
Description: Example-DirectoryLogSubscriptionCustomResource Template.
  This demonstrates how to create a Directory LogSubscription via a Custom Resource.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Function Configuration
        Parameters:
          - DirectoryId
          - LogGroup
    ParameterLabels:
      DirectoryId:
        default: Directory ID
      LogGroup:
        default: Log Group
Parameters:
  DirectoryId:
    Description: Id of the Directory Service
    Type: String
  LogGroup:
    Description: Name of the Log Group
    Type: String
Resources:
  DirectoryLogSubscription:
    Type: Custom::DirectoryLogSubscription
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:DirectoryLogSubscription
      DirectoryId: !Ref DirectoryId
      LogGroup: !Ref LogGroup
