AWSTemplateFormatVersion: 2010-09-09
Description: Example-OpenVPNASImageCustomResource Template.
  This demonstrates how to dynamically get the most recent OpenVPN Access Server Image.
Parameters:
  Region:
    Description: Optional Region, specify to select a region other than the current region
    Type: String
    Default: ''
    AllowedValues:
      - ''
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ca-central-1
      - eu-west-1
      - eu-central-1
      - eu-west-2
      - eu-west-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-2
      - ap-northeast-1
      - ap-south-1
      - sa-east-1
    ConstraintDescription: Must be a valid AWS region or blank.
  License:
    Description: OpenVPN Access Server License. Used to select the OpenVPN Access Server AMI, which limits the number of Users
    Type: String
    Default: OpenVPNAS10
    AllowedValues:
      - ''
      - OpenVPNAS2
      - OpenVPNAS10
      - OpenVPNAS25
      - OpenVPNAS50
      - OpenVPNAS100
    ConstraintDescription: must be OpenVPNAS2, OpenVPNAS10, OpenVPNAS25, OpenVPNAS50 or OpenVPNAS100 or blank.
  Version:
    Description: OpenVPN Access Server Version. Used to select a prior OpenVPN Access Server version if non-blank
    Type: String
    Default: 2.5.2
    AllowedPattern: (^$|^[2-9]\.[0-9]\.[0-9]$)
    ConstraintDescription: must be a version of the form x.y.z or blank.
Conditions:
  ConfigureRegion: !Not [ !Equals [ !Ref Region, '' ]]
  ConfigureLicense: !Not [ !Equals [ !Ref License, '' ]]
  ConfigureVersion: !Not [ !Equals [ !Ref Version, '' ]]
Resources:
  LatestOpenVPNASImage:
    Type: Custom::OpenVPNASImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:OpenVPNASImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
  LatestLicensedOpenVPNASImage:
    Type: Custom::OpenVPNASImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:OpenVPNASImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      License: !If
        - ConfigureLicense
        - !Ref License
        - !Ref AWS::NoValue
  SpecificLicensedOpenVPNASImage:
    Type: Custom::OpenVPNASImage
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:OpenVPNASImage
      Region: !If
        - ConfigureRegion
        - !Ref Region
        - !Ref AWS::NoValue
      License: !If
        - ConfigureLicense
        - !Ref License
        - !Ref AWS::NoValue
      Version: !If
        - ConfigureVersion
        - !Ref Version
        - !Ref AWS::NoValue
Outputs:
  LatestImageId:
    Description: The Latest ImageId
    Value: !Ref LatestOpenVPNASImage
  LatestName:
    Description: The Latest Image Name
    Value: !GetAtt LatestOpenVPNASImage.Name
  LatestLicensedImageId:
    Description: The Latest Licensed ImageId
    Value: !Ref LatestLicensedOpenVPNASImage
  LatestLicensedName:
    Description: The Latest Licensed Image Name
    Value: !GetAtt LatestLicensedOpenVPNASImage.Name
  SpecificLicensedImageId:
    Description: The Specific Licensed ImageId
    Value: !Ref SpecificLicensedOpenVPNASImage
  SpecificLicensedName:
    Description: The Specific Licensed Image Name
    Value: !GetAtt SpecificLicensedOpenVPNASImage.Name
