AWSTemplateFormatVersion: 2010-09-09
Description: Identity-ManagedPolicies Template.
  This creates IAM ManagedPolicies.
Rules:
  ValidateRegion:
    Assertions:
      - Assert: !Equals [ !Ref 'AWS::Region', us-east-1 ]
        AssertDescription: This Template can only be used in Region us-east-1.
Resources:
  LimitedReadOnlyAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: LimitedReadOnlyAccess
      Description: Provides read-only access to a limited set of AWS services and resources.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowLimitedReadOnlyAccess
            Effect: Allow
            Action:
              - application-autoscaling:Describe*
              - autoscaling:Describe*
              - cloudformation:Describe*
              - cloudformation:Get*
              - cloudformation:List*
              - cloudfront:Get*
              - cloudfront:List*
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
              - codebuild:BatchGetBuilds
              - codebuild:BatchGetProjects
              - codebuild:List*
              - codecommit:BatchGetRepositories
              - codecommit:Get*
              - codecommit:GitPull
              - codecommit:List*
              - codedeploy:Batch*
              - codedeploy:Get*
              - codedeploy:List*
              - dynamodb:BatchGetItem
              - dynamodb:DescribeLimits
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:ListTables
              - dynamodb:Query
              - dynamodb:Scan
              - ec2:Describe*
              - ec2:GetConsoleOutput
              - ec2:GetConsoleScreenshot
              - ecs:Describe*
              - ecs:List*
              - elasticache:Describe*
              - elasticache:List*
              - elasticfilesystem:Describe*
              - elasticloadbalancing:Describe*
              - lambda:List*
              - lambda:Get*
              - logs:Describe*
              - logs:Get*
              - logs:FilterLogEvents
              - logs:TestMetricFilter
              - rds:Describe*
              - rds:ListTagsForResource
              - route53:Get*
              - route53:List*
              - s3:Get*
              - s3:List*
              - sns:Get*
              - sns:List*
              - tag:Get*
            Resource: '*'
  UserSelfManagementAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: UserSelfManagementAccess
      Description: Provides limited access to IAM services needed by a user for self-management.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAllUsersToListAccounts
            Effect: Allow
            Action:
              - iam:ListAccountAliases
              - iam:ListUsers
              - iam:GetAccountSummary
            Resource: '*'
          - Sid: AllowIndividualUserToSeeAndManageTheirOwnAccountInformation
            Effect: Allow
            Action:
              - iam:ChangePassword
              - iam:CreateAccessKey
              - iam:CreateLoginProfile
              - iam:DeleteAccessKey
              - iam:DeleteLoginProfile
              - iam:GetAccountPasswordPolicy
              - iam:GetLoginProfile
              - iam:ListAccessKeys
              - iam:UpdateAccessKey
              - iam:UpdateLoginProfile
              - iam:ListSigningCertificates
              - iam:DeleteSigningCertificate
              - iam:UpdateSigningCertificate
              - iam:UploadSigningCertificate
              - iam:ListSSHPublicKeys
              - iam:GetSSHPublicKey
              - iam:DeleteSSHPublicKey
              - iam:UpdateSSHPublicKey
              - iam:UploadSSHPublicKey
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:user/${!aws:username}
          - Sid: AllowIndividualUserToListTheirOwnMFA
            Effect: Allow
            Action:
              - iam:ListVirtualMFADevices
              - iam:ListMFADevices
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:mfa/*
              - !Sub arn:aws:iam::${AWS::AccountId}:user/${!aws:username}
          - Sid: AllowIndividualUserToManageTheirOwnMFA
            Effect: Allow
            Action:
              - iam:CreateVirtualMFADevice
              - iam:DeactivateMFADevice
              - iam:DeleteVirtualMFADevice
              - iam:RequestSmsMfaRegistration
              - iam:FinalizeSmsMfaRegistration
              - iam:EnableMFADevice
              - iam:ResyncMFADevice
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:mfa/${!aws:username}
              - !Sub arn:aws:iam::${AWS::AccountId}:user/${!aws:username}
  UserFolderAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: UserFolderAccess
      Description: Provides access to S3 for per-Region, per-User S3 Folders.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowUserToListBucketsInTheConsole
            Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - s3:GetBucketLocation
            Resource:
              - arn:aws:s3:::*
          - Sid: AllowRootListingOfUsersBucket
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::users-us-east-1-camelz
              - arn:aws:s3:::users-us-east-2-camelz
              - arn:aws:s3:::users-us-west-2-camelz
            Condition:
              StringEquals:
                s3:prefix:
                  - ''
                s3:delimiter:
                  - /
          - Sid: AllowListingOfUserFolder
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::users-us-east-1-camelz
              - arn:aws:s3:::users-us-east-2-camelz
              - arn:aws:s3:::users-us-west-2-camelz
            Condition:
              StringLike:
                s3:prefix:
                  - ${aws:username}/*
          - Sid: AllowAllS3ActionsInUserFolder
            Effect: Allow
            Action:
              - s3:*
            Resource:
              - arn:aws:s3:::users-us-east-1-camelz/${aws:username}/*
              - arn:aws:s3:::users-us-east-2-camelz/${aws:username}/*
              - arn:aws:s3:::users-us-west-2-camelz/${aws:username}/*
  MFARequirement:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: MFARequirement
      Description: Requires use of an MFA device to access services outside of IAM, which is required for a user to self-manage their account.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: BlockAnyAccessOtherThanAboveUnlessSignedInWithMFA
            Effect: Deny
            NotAction: iam:*
            Resource: '*'
            Condition:
              BoolIfExists:
                aws:MultiFactorAuthPresent: false
  ReadOnlyRestrictions:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: ReadOnlyRestrictions
      Description: Restricts the Access provided by the ReadOnlyAccess AWS Managed Policy, to prevent access to sensitive information.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: RestrictReadOnlyAccess
            Effect: Deny
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: '*'
  BillingRestrictions:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: BillingRestrictions
      Description: Reverses the Billing AWS Managed Policy, to prevent access to Billing from Administrators that should not see this infomation.
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: RestrictBilling
            Effect: Deny
            Action:
              - aws-portal:*Billing
              - aws-portal:*Usage
              - aws-portal:*PaymentMethods
              - awsbillingconsole:*Billing
              - awsbillingconsole:*Usage
              - awsbillingconsole:*PaymentMethods
              - budgets:ViewBudget
              - budgets:ModifyBudget
              - cur:*
            Resource: '*'
Outputs:
  LimitedReadOnlyAccess:
    Description: The LimitedReadOnlyAccess ManagedPolicy ARN
    Value: !Ref LimitedReadOnlyAccess
    Export:
      Name: !Sub ${AWS::StackName}-LimitedReadOnlyAccess
  UserSelfManagementAccess:
    Description: The UserSelfManagementAccess ManagedPolicy ARN
    Value: !Ref UserSelfManagementAccess
    Export:
      Name: !Sub ${AWS::StackName}-UserSelfManagementAccess
  UserFolderAccess:
    Description: The UserFolderAccess ManagedPolicy ARN
    Value: !Ref UserFolderAccess
    Export:
      Name: !Sub ${AWS::StackName}-UserFolderAccess
  MFARequirement:
    Description: The MFARequirement ManagedPolicy ARN
    Value: !Ref MFARequirement
    Export:
      Name: !Sub ${AWS::StackName}-MFARequirement
  ReadOnlyRestrictions:
    Description: The ReadOnlyRestrictions ManagedPolicy ARN
    Value: !Ref ReadOnlyRestrictions
    Export:
      Name: !Sub ${AWS::StackName}-ReadOnlyRestrictions
  BillingRestrictions:
    Description: The BillingRestrictions ManagedPolicy ARN
    Value: !Ref BillingRestrictions
    Export:
      Name: !Sub ${AWS::StackName}-BillingRestrictions
