AWSTemplateFormatVersion: 2010-09-09
Description: Join Windows instance to AWS-Active Directory or Microsoft AD (no powershell).
  Create SSM document, IAM Role, SSM doc and EC2 Instance. Attaches EC2 instance to
  AD. Will need to use Domain Logins to RDP in.
Parameters:
  VPCStackName:
    Description: Name of the CloudFormation Stack containing the VPC
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Production-VPC
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  AMIFunctionsStackName:
    Description: Name of the CloudFormation Stack containing the AMI Functions
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: AMIFunctions
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  TopicsStackName:
    Description: Name of the CloudFormation Stack containing Topics
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Topics
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  CodesStackName:
    Description: Name of the CloudFormation Stack containing the Codes Resources
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Codes
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  BaselineStackName:
    Description: Name of the CloudFormation Stack containing the Baseline Resources
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Baseline
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  KeyName:
    Description: Name of an existing KeyPair to enable the Administrator Password
    Type: AWS::EC2::KeyPair::KeyName
    MaxLength: 32
    Default: example
    AllowedPattern: (^$|^[_a-zA-Z0-9]*$)
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  CompanyName:
    Description: Name of the Company associated with the Stack
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: DXC
    AllowedPattern: ^[A-Z][a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  SystemName:
    Description: Name of the System associated with the Stack
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: Prototype
    AllowedPattern: ^[A-Z][a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  AccountName:
    Description: Name of the Account associated with the Stack
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - UAT
      - QA
      - Testing
      - Development
      - Build
      - Core
      - Recovery
      - Log
      - Management
      - Jumpstart
      - Organization
    ConstraintDescription: must be Production, Staging, UAT, QA, Testing, Development, Build, Core, Recovery, Log, Management, Jumpstart or Organization.
  EnvironmentName:
    Description: Name of the Environment associated with the Stack
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - UAT
      - QA
      - Testing
      - Development
      - Build
      - Core
      - Recovery
      - Log
      - Identity
      - Management
      - Organization
    ConstraintDescription: must be Production, Staging, UAT, QA, Testing, Development, Build, Core, Recovery, Log, Identity, Management or Organization.
  OSName:
    Description: The Operating System to use for Instances
    Type: String
    Default: Windows Server 2012 R2
    AllowedValues:
      - Windows Server 2012 R2
      - Windows Server 2016
    ConstraintDescription: must be "Windows Server 2012 R2" or "Windows Server 2016".
  OSDate:
    Description: Optional Operating System Date, specify to select a specific publication date for the Image
    Type: String
    Default: '20191216'
    AllowedPattern: (^$|^20(1[7-9]|[2-9][0-9])(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])$)
    ConstraintDescription: Must be a valid date in YYYYMMDD format.
  DirectoryUtilityName:
    Description: Name of the Directory Utility
    Type: String
    MinLength: 2
    MaxLength: 32
    Default: ActiveDirectory
    AllowedPattern: ^[A-Z][a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters.
  AMI:
    Type: String
    Default: ''
    Description: Windows_Server-2012-R2_RTM-English-64Bit-Base-2019.12.16 Version
  InstanceType:
    Type: String
    Default: t2.medium
    AllowedValues:
    - t1.micro
    - t2.micro
    - t2.small
    - t2.medium
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    - m2.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - c1.medium
    - c1.xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - g2.2xlarge
    - r3.large
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - i2.xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - d2.xlarge
    - d2.2xlarge
    - d2.4xlarge
    - d2.8xlarge
    - hi1.4xlarge
    - hs1.8xlarge
    - cr1.8xlarge
    - cc2.8xlarge
    - cg1.4xlarge
    ConstraintDescription: Must be a valid EC2 instance type.
  ADDirectoryId:
    Default: d-9267163755
    Type: String
    Description: Active DirectoryId. Eg. d-12345679a
  ADDirectoryName:
    Default: u.ad.m1.dxc-ap.com
    Type: String
    Description: Active Directory Name. Eg. my.ad.com
  ADDnsIpAddresses1:
    Default: 10.160.27.228
    Type: String
    Description: Active Directory DNS 1. Eg. 10.0.0.142
  ADDnsIpAddresses2:
    Default: 10.160.31.228
    Type: String
    Description: Active Directory DNS 2. Eg. 10.0.0.143
Resources:
  myssmdocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: '1.2'
        description: Join instances to an AWS Directory Service domain.
        parameters:
          directoryId:
            type: String
            description: "(Required) The ID of the AWS Directory Service directory."
          directoryName:
            type: String
            description: "(Required) The name of the directory; for example, test.example.com"
          dnsIpAddresses:
            type: StringList
            default: []
            description: "(Optional) The IP addresses of the DNS servers in the directory.
              Required when DHCP is not configured. Learn more at http://docs.aws.amazon.com/directoryservice/latest/simple-ad/join_get_dns_addresses.html"
            allowedPattern: "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
        runtimeConfig:
          aws:domainJoin:
            properties:
              directoryId: "{{ directoryId }}"
              directoryName: "{{ directoryName }}"
              dnsIpAddresses: "{{ dnsIpAddresses }}"
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref: myInstanceProfile
      SsmAssociations:
      - DocumentName:
          Ref: myssmdocument
        AssociationParameters:
        - Key: directoryId
          Value:
          - Ref: ADDirectoryId
        - Key: directoryName
          Value:
            - !ImportValue
              Fn::Sub: ${VPCStackName}-VPCDirectoryDomain
        - Key: dnsIpAddresses
          Value:
          - Ref: ADDnsIpAddresses1
          - Ref: ADDnsIpAddresses2
      KeyName:
        Ref: KeyName
      ImageId:
        Ref: AMI
      InstanceType:
        Ref: InstanceType
      Tags:
      - Key: Name
        Value: !Sub ${EnvironmentName}-DuoMFA-Instance
      SubnetId: !ImportValue
        Fn::Sub: ${VPCStackName}-ApplicationSubnetA
      SecurityGroupIds:
      - Fn::GetAtt:
        - InstanceSecurityGroup
        - GroupId
  myEC2SSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      RoleName: !Sub ${EnvironmentName}-DuoMFA-Role
      # RoleName: DemoEC2SSMRole
  myInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      # - DemoEC2SSMRole
      - !Sub ${EnvironmentName}-DuoMFA-Role
      InstanceProfileName: myEC2SSMRole
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !ImportValue
          Fn::Sub: ${VPCStackName}-VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3389'
          ToPort: '3389'
          SourceSecurityGroupId: !ImportValue
            Fn::Sub: ${EnvironmentName}-OpenVPNAS-InstanceSecurityGroup
          # CidrIp: !ImportValue
          #   Fn::Sub: ${EnvironmentName}-OpenVPNAS-InstanceSecurityGroup
          Description: !Sub ${EnvironmentName}-OpenVPNAS-InstanceSecurityGroup (RDP)
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-DuoMFA-InstanceSecurityGroup
