AWSTemplateFormatVersion: 2010-09-09
2	Description: Application-CICD-User-Policies Template.
3	  This creates Customer IAM-User-Policies.
4	Resources:
5	  DMSACodeCommitUserPolicy:
6	    Type: AWS::IAM::ManagedPolicy
7	    Properties:
8	      ManagedPolicyName: DMSACodeCommitUserPolicy
9	      Description: Provides partial access to DMSA AWS services and resources, needed for DMSA CodeCommit UserPolicy
10	      Path: /
11	      PolicyDocument:
12	        Version: 2012-10-17
13	        Statement:
14	          - Sid: VisualEditor0
15	            Effect: Allow
16	            Action:
17	              - 'codecommit:CreateBranch'
18	              - 'codecommit:TagResource'
19	              - 'codecommit:ListPullRequests'
20	              - 'codecommit:UpdatePullRequestApprovalRuleContent'
21	              - 'codecommit:PutFile'
22	              - 'codecommit:GetPullRequestApprovalStates'
23	              - 'codecommit:CreateCommit'
24	              - 'codecommit:ListTagsForResource'
25	              - 'codecommit:BatchDescribeMergeConflicts'
26	              - 'codecommit:GetCommentsForComparedCommit'
27	              - 'codecommit:GetComment'
28	              - 'codecommit:UpdateComment'
29	              - 'codecommit:UpdateRepositoryDescription'
30	              - 'codecommit:CreatePullRequest'
31	              - 'codecommit:UpdatePullRequestApprovalState'
32	              - 'codecommit:GetPullRequestOverrideState'
33	              - 'codecommit:PostCommentForPullRequest'
34	              - 'codecommit:GetRepositoryTriggers'
35	              - 'codecommit:UpdatePullRequestDescription'
36	              - 'codecommit:UntagResource'
37	              - 'codecommit:UpdateApprovalRuleTemplateContent'
38	              - 'codecommit:GetFile'
39	              - 'codecommit:GetDifferences'
40	              - 'codecommit:GetRepository'
41	              - 'codecommit:GetMergeConflicts'
42	              - 'codecommit:GetMergeCommit'
43	              - 'codecommit:GitPush'
44	              - 'codecommit:GetMergeOptions'
45	              - 'codecommit:AssociateApprovalRuleTemplateWithRepository'
46	              - 'codecommit:BatchAssociateApprovalRuleTemplateWithRepositories'
47	              - 'codecommit:GetReferences'
48	              - 'codecommit:ListRepositories'
49	              - 'codecommit:UpdatePullRequestTitle'
50	              - 'codecommit:GetCommit'
51	              - 'codecommit:GetCommitHistory'
52	              - 'codecommit:GetCommitsFromMergeBase'
53	              - 'codecommit:BatchGetCommits'
54	              - 'codecommit:TestRepositoryTriggers'
55	              - 'codecommit:UpdatePullRequestStatus'
56	              - 'codecommit:GetPullRequest'
57	              - 'codecommit:PutRepositoryTriggers'
58	              - 'codecommit:UploadArchive'
59	              - 'codecommit:ListAssociatedApprovalRuleTemplatesForRepository'
60	              - 'codecommit:ListBranches'
61	              - 'codecommit:GitPull'
62	              - 'codecommit:BatchGetRepositories'
63	              - 'codecommit:BatchDisassociateApprovalRuleTemplateFromRepositories'
64	              - 'codecommit:GetFolder'
65	              - 'codecommit:PostCommentReply'
66	              - 'codecommit:GetBranch'
67	              - 'codecommit:DisassociateApprovalRuleTemplateFromRepository'
68	              - 'codecommit:UpdateApprovalRuleTemplateDescription'
69	            Resource: '*'
70	  DMSACodeBuildUserPolicy:
71	    Type: AWS::IAM::ManagedPolicy
72	    Properties:
73	      ManagedPolicyName: DMSACodeBuildUserPolicy
74	      Description: Provides partial access to DMSA AWS services and resources, needed for DMSA CodeBuild UserPolicy
75	      Path: /
76	      PolicyDocument:
77	        Version: 2012-10-17
78	        Statement:
79	          - Sid: VisualEditor0
80	            Effect: Allow
81	            Action:
82	              - 'codebuild:ListReportsForReportGroup'
83	              - 'codebuild:DescribeTestCases'
84	              - 'codebuild:GetResourcePolicy'
85	              - 'codebuild:StopBuild'
86	              - 'codebuild:ListReportGroups'
87	              - 'codebuild:ListBuildsForProject'
88	              - 'codebuild:UpdateWebhook'
89	              - 'codebuild:UpdateProject'
90	              - 'codebuild:BatchGetBuilds'
91	              - 'codebuild:CreateReport'
92	              - 'codebuild:UpdateReport'
93	              - 'codebuild:ImportSourceCredentials'
94	              - 'codebuild:ListReports'
95	              - 'codebuild:ListProjects'
96	              - 'codebuild:BatchGetReportGroups'
97	              - 'codebuild:ListConnectedOAuthAccounts'
98	              - 'codebuild:BatchGetProjects'
99	              - 'codebuild:InvalidateProjectCache'
100	              - 'codebuild:BatchGetReports'
101	              - 'codebuild:CreateWebhook'
102	              - 'codebuild:UpdateReportGroup'
103	              - 'codebuild:CreateReportGroup'
104	              - 'codebuild:PutResourcePolicy'
105	              - 'codebuild:ListBuilds'
106	              - 'codebuild:StartBuild'
107	              - 'codebuild:BatchPutTestCases'
108	            Resource: '*'
109	  DMSACodeDeployUserPolicy:
110	    Type: AWS::IAM::ManagedPolicy
111	    Properties:
112	      ManagedPolicyName: DMSACodeDeployUserPolicy
113	      Description: Provides partial access to DMSA AWS services and resources, needed for DMSA CodeDeploy UserPolicy
114	      Path: /
115	      PolicyDocument:
116	        Version: 2012-10-17
117	        Statement:
118	          - Sid: VisualEditor0
119	            Effect: Allow
120	            Action:
121	              - 'codedeploy:BatchGetDeploymentGroups'
122	              - 'codedeploy:PutLifecycleEventHookExecutionStatus'
123	              - 'codedeploy:CreateApplication'
124	              - 'codedeploy:CreateDeployment'
125	              - 'codedeploy:GetApplicationRevision'
126	              - 'codedeploy:GetDeploymentConfig'
127	              - 'codedeploy:DeregisterOnPremisesInstance'
128	              - 'codedeploy:CreateDeploymentConfig'
129	              - 'codedeploy:UpdateDeploymentGroup'
130	              - 'codedeploy:CreateDeploymentGroup'
131	              - 'codedeploy:ListApplications'
132	              - 'codedeploy:ListOnPremisesInstances'
133	              - 'codedeploy:ListDeploymentInstances'
134	              - 'codedeploy:ListTagsForResource'
135	              - 'codedeploy:RegisterOnPremisesInstance'
136	              - 'codedeploy:ListGitHubAccountTokenNames'
137	              - 'codedeploy:BatchGetApplications'
138	              - 'codedeploy:ListDeploymentConfigs'
139	              - 'codedeploy:GetApplication'
140	              - 'codedeploy:SkipWaitTimeForInstanceTermination'
141	              - 'codedeploy:TagResource'
142	              - 'codedeploy:GetDeploymentGroup'
143	              - 'codedeploy:UpdateApplication'
144	              - 'codedeploy:RegisterApplicationRevision'
145	              - 'codedeploy:BatchGetDeploymentTargets'
146	              - 'codedeploy:ListDeployments'
147	              - 'codedeploy:GetDeploymentTarget'
148	              - 'codedeploy:StopDeployment'
149	              - 'codedeploy:ListDeploymentTargets'
150	              - 'codedeploy:ContinueDeployment'
151	              - 'codedeploy:AddTagsToOnPremisesInstances'
152	              - 'codedeploy:BatchGetDeployments'
153	              - 'codedeploy:BatchGetApplicationRevisions'
154	              - 'codedeploy:BatchGetDeploymentInstances'
155	              - 'codedeploy:ListDeploymentGroups'
156	              - 'codedeploy:GetDeployment'
157	              - 'codedeploy:ListApplicationRevisions'
158	              - 'codedeploy:BatchGetOnPremisesInstances'
159	            Resource: '*'
160	  DMSACodePipelineUserPolicy:
161	    Type: AWS::IAM::ManagedPolicy
162	    Properties:
163	      ManagedPolicyName: DMSACodePipelineUserPolicy
164	      Description: Provides partial access to DMSA AWS services and resources, needed for DMSACode Pipeline UserPolicy
165	      Path: /
166	      PolicyDocument:
167	        Version: 2012-10-17
168	        Statement:
169	          - Sid: VisualEditor0
170	            Effect: Allow
171	            Action:
172	              - 'codepipeline:ListPipelineExecutions'
173	              - 'codepipeline:ListActionExecutions'
174	              - 'codepipeline:CreatePipeline'
175	              - 'codepipeline:AcknowledgeThirdPartyJob'
176	              - 'codepipeline:CreateCustomActionType'
177	              - 'codepipeline:ListTagsForResource'
178	              - 'codepipeline:TagResource'
179	              - 'codepipeline:RetryStageExecution'
180	              - 'codepipeline:PutJobFailureResult'
181	              - 'codepipeline:ListPipelines'
182	              - 'codepipeline:GetPipeline'
183	              - 'codepipeline:RegisterWebhookWithThirdParty'
184	              - 'codepipeline:ListWebhooks'
185	              - 'codepipeline:StartPipelineExecution'
186	              - 'codepipeline:PutJobSuccessResult'
187	              - 'codepipeline:GetThirdPartyJobDetails'
188	              - 'codepipeline:GetJobDetails'
189	              - 'codepipeline:PutApprovalResult'
190	              - 'codepipeline:StopPipelineExecution'
191	              - 'codepipeline:AcknowledgeJob'
192	              - 'codepipeline:UpdatePipeline'
193	              - 'codepipeline:GetPipelineState'
194	              - 'codepipeline:GetPipelineExecution'
195	              - 'codepipeline:PutActionRevision'
196	              - 'codepipeline:ListActionTypes'
197	            Resource: '*'
198	Outputs:
199	  DMSACodeCommitUserPolicy:
200	    Description: The DMSA CodeCommit UserPolicy
201	    Value: !Ref DMSACodeCommitUserPolicy
202	    Export:
203	      Name: !Sub ${AWS::StackName}-DMSACodeCommitUserPolicy
204	  DMSACodeBuildUserPolicy:
205	    Description: The DMSA CodeBuild UserPolicy
206	    Value: !Ref DMSACodeBuildUserPolicy
207	    Export:
208	      Name: !Sub ${AWS::StackName}-DMSACodeBuildUserPolicy
209	  DMSACodeDeployUserPolicy:
210	    Description: The DMSA CodeDeploy UserPolicy
211	    Value: !Ref DMSACodeDeployUserPolicy
212	    Export:
213	      Name: !Sub ${AWS::StackName}-DMSACodeDeployUserPolicy
214	  DMSACodePipelineUserPolicy:
215	    Description: The DMSACode Pipeline UserPolicy
216	    Value: !Ref DMSACodePipelineUserPolicy
217	    Export:
218	      Name: !Sub ${AWS::StackName}-DMSACodePipelineUserPolicy
