AWSTemplateFormatVersion: 2010-09-09
Description: Example-DirectoryAliasCustomResource Template.
  This demonstrates how to create a Directory Alias via a Custom Resource.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Function Configuration
        Parameters:
          - DirectoryId
          - DirectoryAlias
    ParameterLabels:
      DirectoryId:
        default: Directory ID
      DirectoryAlias:
        default: Directory Alias
Parameters:
  DirectoryId:
    Description: Id of the Directory Service
    Type: String
  DirectoryAlias:
    Description: Alias of the Directory Service
    Type: String
Resources:
  DirectoryAlias:
    Type: Custom::DirectoryAlias
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:DirectoryAlias
      DirectoryId: !Ref DirectoryId
      DirectoryAlias: !Ref DirectoryAlias
