AWSTemplateFormatVersion: 2010-09-09
Description: Example-TestingExports Template.
  This is a testing template which creates 60 Exports to test Export pagination logic.
Resources:
  DummyGroup:
    Type: AWS::IAM::Group
    Properties:
      Path: /
Outputs:
  Output00:
    Description: Output 00
    Value: '00'
    Export:
      Name: !Sub ${AWS::StackName}-Output00
  Output01:
    Description: Output 01
    Value: '01'
    Export:
      Name: !Sub ${AWS::StackName}-Output01
  Output02:
    Description: Output 02
    Value: '02'
    Export:
      Name: !Sub ${AWS::StackName}-Output02
  Output03:
    Description: Output 03
    Value: '03'
    Export:
      Name: !Sub ${AWS::StackName}-Output03
  Output04:
    Description: Output 04
    Value: '04'
    Export:
      Name: !Sub ${AWS::StackName}-Output04
  Output05:
    Description: Output 05
    Value: '05'
    Export:
      Name: !Sub ${AWS::StackName}-Output05
  Output06:
    Description: Output 06
    Value: '06'
    Export:
      Name: !Sub ${AWS::StackName}-Output06
  Output07:
    Description: Output 07
    Value: '07'
    Export:
      Name: !Sub ${AWS::StackName}-Output07
  Output08:
    Description: Output 08
    Value: '08'
    Export:
      Name: !Sub ${AWS::StackName}-Output08
  Output09:
    Description: Output 09
    Value: '09'
    Export:
      Name: !Sub ${AWS::StackName}-Output09
  Output10:
    Description: Output 10
    Value: '10'
    Export:
      Name: !Sub ${AWS::StackName}-Output10
  Output11:
    Description: Output 11
    Value: '11'
    Export:
      Name: !Sub ${AWS::StackName}-Output11
  Output12:
    Description: Output 12
    Value: '12'
    Export:
      Name: !Sub ${AWS::StackName}-Output12
  Output13:
    Description: Output 13
    Value: '13'
    Export:
      Name: !Sub ${AWS::StackName}-Output13
  Output14:
    Description: Output 14
    Value: '14'
    Export:
      Name: !Sub ${AWS::StackName}-Output14
  Output15:
    Description: Output 15
    Value: '15'
    Export:
      Name: !Sub ${AWS::StackName}-Output15
  Output16:
    Description: Output 16
    Value: '16'
    Export:
      Name: !Sub ${AWS::StackName}-Output16
  Output17:
    Description: Output 17
    Value: '17'
    Export:
      Name: !Sub ${AWS::StackName}-Output17
  Output18:
    Description: Output 18
    Value: '18'
    Export:
      Name: !Sub ${AWS::StackName}-Output18
  Output19:
    Description: Output 19
    Value: '19'
    Export:
      Name: !Sub ${AWS::StackName}-Output19
  Output20:
    Description: Output 20
    Value: '20'
    Export:
      Name: !Sub ${AWS::StackName}-Output20
  Output21:
    Description: Output 21
    Value: '21'
    Export:
      Name: !Sub ${AWS::StackName}-Output21
  Output22:
    Description: Output 22
    Value: '22'
    Export:
      Name: !Sub ${AWS::StackName}-Output22
  Output23:
    Description: Output 23
    Value: '23'
    Export:
      Name: !Sub ${AWS::StackName}-Output23
  Output24:
    Description: Output 24
    Value: '24'
    Export:
      Name: !Sub ${AWS::StackName}-Output24
  Output25:
    Description: Output 25
    Value: '25'
    Export:
      Name: !Sub ${AWS::StackName}-Output25
  Output26:
    Description: Output 26
    Value: '26'
    Export:
      Name: !Sub ${AWS::StackName}-Output26
  Output27:
    Description: Output 27
    Value: '27'
    Export:
      Name: !Sub ${AWS::StackName}-Output27
  Output28:
    Description: Output 28
    Value: '28'
    Export:
      Name: !Sub ${AWS::StackName}-Output28
  Output29:
    Description: Output 29
    Value: '29'
    Export:
      Name: !Sub ${AWS::StackName}-Output29
  Output30:
    Description: Output 30
    Value: '30'
    Export:
      Name: !Sub ${AWS::StackName}-Output30
  Output31:
    Description: Output 31
    Value: '31'
    Export:
      Name: !Sub ${AWS::StackName}-Output31
  Output32:
    Description: Output 32
    Value: '32'
    Export:
      Name: !Sub ${AWS::StackName}-Output32
  Output33:
    Description: Output 33
    Value: '33'
    Export:
      Name: !Sub ${AWS::StackName}-Output33
  Output34:
    Description: Output 34
    Value: '34'
    Export:
      Name: !Sub ${AWS::StackName}-Output34
  Output35:
    Description: Output 35
    Value: '35'
    Export:
      Name: !Sub ${AWS::StackName}-Output35
  Output36:
    Description: Output 36
    Value: '36'
    Export:
      Name: !Sub ${AWS::StackName}-Output36
  Output37:
    Description: Output 37
    Value: '37'
    Export:
      Name: !Sub ${AWS::StackName}-Output37
  Output38:
    Description: Output 38
    Value: '38'
    Export:
      Name: !Sub ${AWS::StackName}-Output38
  Output39:
    Description: Output 39
    Value: '39'
    Export:
      Name: !Sub ${AWS::StackName}-Output39
  Output40:
    Description: Output 40
    Value: '40'
    Export:
      Name: !Sub ${AWS::StackName}-Output40
  Output41:
    Description: Output 41
    Value: '41'
    Export:
      Name: !Sub ${AWS::StackName}-Output41
  Output42:
    Description: Output 42
    Value: '42'
    Export:
      Name: !Sub ${AWS::StackName}-Output42
  Output43:
    Description: Output 43
    Value: '43'
    Export:
      Name: !Sub ${AWS::StackName}-Output43
  Output44:
    Description: Output 44
    Value: '44'
    Export:
      Name: !Sub ${AWS::StackName}-Output44
  Output45:
    Description: Output 45
    Value: '45'
    Export:
      Name: !Sub ${AWS::StackName}-Output45
  Output46:
    Description: Output 46
    Value: '46'
    Export:
      Name: !Sub ${AWS::StackName}-Output46
  Output47:
    Description: Output 47
    Value: '47'
    Export:
      Name: !Sub ${AWS::StackName}-Output47
  Output48:
    Description: Output 48
    Value: '48'
    Export:
      Name: !Sub ${AWS::StackName}-Output48
  Output49:
    Description: Output 49
    Value: '49'
    Export:
      Name: !Sub ${AWS::StackName}-Output49
  Output50:
    Description: Output 50
    Value: '50'
    Export:
      Name: !Sub ${AWS::StackName}-Output50
  Output51:
    Description: Output 51
    Value: '51'
  Output52:
    Description: Output 52
    Value: '52'
  Output53:
    Description: Output 53
    Value: '53'
  Output54:
    Description: Output 54
    Value: '54'
  Output55:
    Description: Output 55
    Value: '55'
  Output56:
    Description: Output 56
    Value: '56'
  Output57:
    Description: Output 57
    Value: '57'
  Output58:
    Description: Output 58
    Value: '58'
  Output59:
    Description: Output 59
    Value: '59'
