AWSTemplateFormatVersion: 2010-09-09
Description: Example-DirectoryConditionalForwarderCustomResource Template.
  This demonstrates how to create a Directory ConditionalForwarder via a Custom Resource.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Function Configuration
        Parameters:
          - DirectoryId
          - Domain
          - VpcCidrBlock
    ParameterLabels:
      DirectoryId:
        default: Directory ID
      Domain:
        default: Domain
      VpcCidrBlock:
        default: VPC CIDR Block
Parameters:
  DirectoryId:
    Description: Id of the Directory Service
    Type: String
  Domain:
    Description: DNS Domain of the Conditional Forwarder
    Type: String
  VpcCidrBlock:
    Description: VPC CIDR Block, used to calculate the address of Amazon's DNS Servers
    Type: String
Resources:
  DirectoryConditionalForwarder:
    Type: Custom::DirectoryConditionalForwarder
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:DirectoryConditionalForwarder
      DirectoryId: !Ref DirectoryId
      Domain: !Ref Domain
      VpcCidrBlock: !Ref VpcCidrBlock
