AWSTemplateFormatVersion: 2010-09-09
Description: ReferenceFunctions Template.
  This creates Lambda Functions which implement References to various types of Resources which may exist in different
  Regions and/or Accounts. There are two variants of this concept. The first does a cross-account lookup of a non-Shared
  Resource. The second works with Resource Access Manager to lookup a Resource shared with the current Account.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - LayersStackName
          - BucketsStackName
          - TopicsStackName
      - Label:
          default: Function Configuration
        Parameters:
          - RoleReferenceFunctionS3Key
          - RoleReferenceLogRetention
          - VpcReferenceFunctionS3Key
          - VpcReferenceLogRetention
          - SubnetReferenceFunctionS3Key
          - SubnetReferenceLogRetention
          - SecurityGroupReferenceFunctionS3Key
          - SecurityGroupReferenceLogRetention
          - StackExportReferenceFunctionS3Key
          - StackExportReferenceLogRetention
          - StackExportsReferenceFunctionS3Key
          - StackExportsReferenceLogRetention
          - TransitGatewayReferenceFunctionS3Key
          - TransitGatewayReferenceLogRetention
    ParameterLabels:
      LayersStackName:
        default: Layers Stack Name
      BucketsStackName:
        default: Buckets Stack Name
      TopicsStackName:
        default: Topics Stack Name
      RoleReferenceFunctionS3Key:
        default: RoleReference Function S3 Key
      RoleReferenceLogRetention:
        default: RoleReference Log Retention
      VpcReferenceFunctionS3Key:
        default: VpcReference Function S3 Key
      VpcReferenceLogRetention:
        default: VpcReference Log Retention
      SubnetReferenceFunctionS3Key:
        default: SubnetReference Function S3 Key
      SubnetReferenceLogRetention:
        default: SubnetReference Log Retention
      SecurityGroupReferenceFunctionS3Key:
        default: SecurityGroupReference Function S3 Key
      SecurityGroupReferenceLogRetention:
        default: SecurityGroupReference Log Retention
      StackExportReferenceFunctionS3Key:
        default: StackExportReference Function S3 Key
      StackExportReferenceLogRetention:
        default: StackExportReference Log Retention
      StackExportsReferenceFunctionS3Key:
        default: StackExportsReference Function S3 Key
      StackExportsReferenceLogRetention:
        default: StackExportsReference Log Retention
      TransitGatewayReferenceFunctionS3Key:
        default: TransitGatewayReference Function S3 Key
      TransitGatewayReferenceLogRetention:
        default: TransitGatewayReference Log Retention
Parameters:
  LayersStackName:
    Description: Name of the CloudFormation Stack containing Layers
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Layers
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  BucketsStackName:
    Description: Name of the CloudFormation Stack containing Buckets
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Buckets
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  TopicsStackName:
    Description: Name of the CloudFormation Stack containing Topics
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Topics
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  RoleReferenceFunctionS3Key:
    Description: Key of Object within the S3 Bucket containing the RoleReference Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: RoleReference.zip
    AllowedPattern: ^RoleReference(/[0-9a-f]{32})?\.zip$
    ConstraintDescription: must be RoleReference.zip, or RoleReference/<md5_hash>.zip.
  RoleReferenceLogRetention:
    Description: Number of days to retain CloudWatch Log Events for the RoleReference Lambda Function
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
    ConstraintDescription: must be 1, 3, 5, 7, 14, 30, 60 or 90.
  VpcReferenceFunctionS3Key:
    Description: Key of Object within the S3 Bucket containing the VpcReference Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: VpcReference.zip
    AllowedPattern: ^VpcReference(/[0-9a-f]{32})?\.zip$
    ConstraintDescription: must be VpcReference.zip, or VpcReference/<md5_hash>.zip.
  VpcReferenceLogRetention:
    Description: Number of days to retain CloudWatch Log Events for the VpcReference Lambda Function
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
    ConstraintDescription: must be 1, 3, 5, 7, 14, 30, 60 or 90.
  SubnetReferenceFunctionS3Key:
    Description: Key of Object within the S3 Bucket containing the SubnetReference Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: SubnetReference.zip
    AllowedPattern: ^SubnetReference(/[0-9a-f]{32})?\.zip$
    ConstraintDescription: must be SubnetReference.zip, or SubnetReference/<md5_hash>.zip.
  SubnetReferenceLogRetention:
    Description: Number of days to retain CloudWatch Log Events for the SubnetReference Lambda Function
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
    ConstraintDescription: must be 1, 3, 5, 7, 14, 30, 60 or 90.
  SecurityGroupReferenceFunctionS3Key:
    Description: Key of Object within the S3 Bucket containing the SecurityGroupReference Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: SecurityGroupReference.zip
    AllowedPattern: ^SecurityGroupReference(/[0-9a-f]{32})?\.zip$
    ConstraintDescription: must be SecurityGroupReference.zip, or SecurityGroupReference/<md5_hash>.zip.
  SecurityGroupReferenceLogRetention:
    Description: Number of days to retain CloudWatch Log Events for the SecurityGroupReference Lambda Function
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
    ConstraintDescription: must be 1, 3, 5, 7, 14, 30, 60 or 90.
  StackExportReferenceFunctionS3Key:
    Description: Key of Object within the S3 Bucket containing the StackExportReference Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: StackExportReference.zip
    AllowedPattern: ^StackExportReference(/[0-9a-f]{32})?\.zip$
    ConstraintDescription: must be StackExportReference.zip, or StackExportReference/<md5_hash>.zip.
  StackExportReferenceLogRetention:
    Description: Number of days to retain CloudWatch Log Events for the StackExportReference Lambda Function
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
    ConstraintDescription: must be 1, 3, 5, 7, 14, 30, 60 or 90.
  StackExportsReferenceFunctionS3Key:
    Description: Key of Object within the S3 Bucket containing the StackExportsReference Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: StackExportsReference.zip
    AllowedPattern: ^StackExportsReference(/[0-9a-f]{32})?\.zip$
    ConstraintDescription: must be StackExportsReference.zip, or StackExportsReference/<md5_hash>.zip.
  StackExportsReferenceLogRetention:
    Description: Number of days to retain CloudWatch Log Events for the StackExportsReference Lambda Function
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
    ConstraintDescription: must be 1, 3, 5, 7, 14, 30, 60 or 90.
  TransitGatewayReferenceFunctionS3Key:
    Description: Key of Object within the S3 Bucket containing the TransitGatewayReference Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: TransitGatewayReference.zip
    AllowedPattern: ^TransitGatewayReference(/[0-9a-f]{32})?\.zip$
    ConstraintDescription: must be TransitGatewayReference.zip, or TransitGatewayReference/<md5_hash>.zip.
  TransitGatewayReferenceLogRetention:
    Description: Number of days to retain CloudWatch Log Events for the TransitGatewayReference Lambda Function
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
    ConstraintDescription: must be 1, 3, 5, 7, 14, 30, 60 or 90.
Resources:
  ReferenceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LocalReferencePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowGetRole
                Effect: Allow
                Action:
                  - iam:GetRole
                Resource: '*'
              - Sid: AllowDescribeVpcs
                Effect: Allow
                Action:
                  - ec2:DescribeVpcs
                Resource: '*'
              - Sid: AllowDescribeSubnets
                Effect: Allow
                Action:
                  - ec2:DescribeSubnets
                Resource: '*'
              - Sid: AllowDescribeSecurityGroups
                Effect: Allow
                Action:
                  - ec2:DescribeSecurityGroups
                Resource: '*'
              - Sid: AllowListExports
                Effect: Allow
                Action:
                  - cloudformation:ListExports
                Resource: '*'
              - Sid: AllowDescribeStacks
                Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                Resource: '*'
              - Sid: AllowListBuckets
                Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource: '*'
        - PolicyName: RemoteReferencePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - !Sub arn:aws:iam::*:role/ReferenceRole
  RoleReferenceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/RoleReference
      RetentionInDays: !Ref RoleReferenceLogRetention
  RoleReferenceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: RoleReference
      Description: A Lambda function that returns information about an IAM Role in another Region and/or Account.
      Role: !GetAtt ReferenceRole.Arn
      Runtime: nodejs12.x
      Timeout: 30
      Layers:
        - !ImportValue
            Fn::Sub: ${LayersStackName}-AsyncCustomResourceLayerVersionArn
      Handler: RoleReference.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref RoleReferenceFunctionS3Key
    DependsOn: RoleReferenceLogGroup
  VpcReferenceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/VpcReference
      RetentionInDays: !Ref VpcReferenceLogRetention
  VpcReferenceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: VpcReference
      Description: A Lambda function that returns information about an EC2 VPC in another Region and/or Account.
      Role: !GetAtt ReferenceRole.Arn
      Runtime: nodejs12.x
      Timeout: 30
      Layers:
        - !ImportValue
            Fn::Sub: ${LayersStackName}-AsyncCustomResourceLayerVersionArn
      Handler: VpcReference.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref VpcReferenceFunctionS3Key
    DependsOn: VpcReferenceLogGroup
  SubnetReferenceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/SubnetReference
      RetentionInDays: !Ref SubnetReferenceLogRetention
  SubnetReferenceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SubnetReference
      Description: A Lambda function that returns information about an EC2 Subnet in another Region and/or Account.
      Role: !GetAtt ReferenceRole.Arn
      Runtime: nodejs12.x
      Timeout: 30
      Layers:
        - !ImportValue
            Fn::Sub: ${LayersStackName}-AsyncCustomResourceLayerVersionArn
      Handler: SubnetReference.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref SubnetReferenceFunctionS3Key
    DependsOn: SubnetReferenceLogGroup
  SecurityGroupReferenceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/SecurityGroupReference
      RetentionInDays: !Ref SecurityGroupReferenceLogRetention
  SecurityGroupReferenceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SecurityGroupReference
      Description: A Lambda function that returns information about an EC2 Security Group in another Region and/or Account.
      Role: !GetAtt ReferenceRole.Arn
      Runtime: nodejs12.x
      Timeout: 30
      Layers:
        - !ImportValue
            Fn::Sub: ${LayersStackName}-AsyncCustomResourceLayerVersionArn
      Handler: SecurityGroupReference.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref SecurityGroupReferenceFunctionS3Key
    DependsOn: SecurityGroupReferenceLogGroup
  StackExportReferenceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/StackExportReference
      RetentionInDays: !Ref StackExportReferenceLogRetention
  StackExportReferenceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: StackExportReference
      Description: A Lambda function that returns the value of a single Stack Export in another Region and/or Account.
      Role: !GetAtt ReferenceRole.Arn
      Runtime: nodejs12.x
      Timeout: 30
      Layers:
        - !ImportValue
            Fn::Sub: ${LayersStackName}-AsyncCustomResourceLayerVersionArn
      Handler: StackExportReference.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref StackExportReferenceFunctionS3Key
    DependsOn: StackExportReferenceLogGroup
  StackExportsReferenceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/StackExportsReference
      RetentionInDays: !Ref StackExportsReferenceLogRetention
  StackExportsReferenceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: StackExportsReference
      Description: A Lambda function that returns the values of all Exports for a single CloudFormation Stack in another Region and/or Account.
      Role: !GetAtt ReferenceRole.Arn
      Runtime: nodejs12.x
      Timeout: 30
      Layers:
        - !ImportValue
            Fn::Sub: ${LayersStackName}-AsyncCustomResourceLayerVersionArn
      Handler: StackExportsReference.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref StackExportsReferenceFunctionS3Key
    DependsOn: StackExportsReferenceLogGroup
  TransitGatewayReferenceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TransitGatewayReferencePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ram:GetResourceShares
                  - ram:GetResourceShareInvitations
                  - ram:AcceptResourceShareInvitation
                  - ram:ListResources
                  - ec2:DescribeTransitGateways
                Resource: '*'
  TransitGatewayReferenceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/TransitGatewayReference
      RetentionInDays: !Ref TransitGatewayReferenceLogRetention
  TransitGatewayReferenceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TransitGatewayReference
      Description: A Lambda function that creates an alias for a directory service.
      Role: !GetAtt TransitGatewayReferenceRole.Arn
      Runtime: nodejs12.x
      Timeout: 30
      Layers:
        - !ImportValue
            Fn::Sub: ${LayersStackName}-AsyncCustomResourceLayerVersionArn
      Handler: TransitGatewayReference.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref TransitGatewayReferenceFunctionS3Key
    DependsOn: TransitGatewayReferenceLogGroup
Outputs:
  RoleReferenceFunctionArn:
    Description: The RoleReference Lambda Function ARN
    Value: !GetAtt RoleReferenceFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-RoleReferenceFunctionArn
  VpcReferenceFunctionArn:
    Description: The VpcReference Lambda Function ARN
    Value: !GetAtt VpcReferenceFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-VpcReferenceFunctionArn
  SubnetReferenceFunctionArn:
    Description: The SubnetReference Lambda Function ARN
    Value: !GetAtt SubnetReferenceFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-SubnetReferenceFunctionArn
  SecurityGroupReferenceFunctionArn:
    Description: The SecurityGroupReference Lambda Function ARN
    Value: !GetAtt SecurityGroupReferenceFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-SecurityGroupReferenceFunctionArn
  StackExportReferenceFunctionArn:
    Description: The StackExportReference Lambda Function ARN
    Value: !GetAtt StackExportReferenceFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-StackExportReferenceFunctionArn
  StackExportsReferenceFunctionArn:
    Description: The StackExportsReference Lambda Function ARN
    Value: !GetAtt StackExportsReferenceFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-StackExportsReferenceFunctionArn
  TransitGatewayReferenceFunctionArn:
    Description: The TransitGatewayReference Lambda Function ARN
    Value: !GetAtt TransitGatewayReferenceFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-TransitGatewayReferenceFunctionArn
