AWSTemplateFormatVersion: 2010-09-09
Description: Roles Template.
  This creates IAM Roles. These are not Application specific - Roles created here are for Federated Identity and Cross-Account Access. Roles should be kept in 1:1 sync with Groups, to insure IAM Users and Federated Users have the same permissions.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - ManagedPoliciesStackName
      - Label:
          default: Identity Provider Dependencies
        Parameters:
          - SamlProviderName
    ParameterLabels:
      ManagedPoliciesStackName:
        default: Managed Policies Stack Name
      SamlProviderName:
        default: SAML Provider Name
Parameters:
  ManagedPoliciesStackName:
    Description: Name of the CloudFormation Stack containing ManagedPolicies
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: ManagedPolicies
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  SamlProviderName:
    Description: Name of the SAML Provider
    Type: String
    Default: ''
    AllowedPattern: (^$|^[-.a-zA-Z0-9]{2,64}$)
    ConstraintDescription: must begin with a letter and contain alphanumeric characters, dashes and periods, or blank.
Rules:
  ValidateRegion:
    Assertions:
      - Assert: !Equals [ !Ref 'AWS::Region', us-east-1 ]
        AssertDescription: This Template can only be used in Region us-east-1.
Conditions:
  ConfigureSamlRoles: !Not [ !Equals [ !Ref SamlProviderName, '' ]]
Resources:
  AdministratorsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Administrators
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/${SamlProviderName}
            Action:
              - sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
    Condition: ConfigureSamlRoles
  NetworkAdministratorsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: NetworkAdministrators
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/${SamlProviderName}
            Action:
              - sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/NetworkAdministrator
    Condition: ConfigureSamlRoles
  SystemAdministratorsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SystemAdministrators
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/${SamlProviderName}
            Action:
              - sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/SystemAdministrator
    Condition: ConfigureSamlRoles
  DatabaseAdministratorsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DatabaseAdministrators
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/${SamlProviderName}
            Action:
              - sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/DatabaseAdministrator
    Condition: ConfigureSamlRoles
  SecurityAdministratorsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SecurityAdministrators
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/${SamlProviderName}
            Action:
              - sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
    Condition: ConfigureSamlRoles
  DevelopersRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Developers
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/${SamlProviderName}
            Action:
              - sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
        - !ImportValue
          Fn::Sub: ${ManagedPoliciesStackName}-UserSelfManagementAccess
        - !ImportValue
          Fn::Sub: ${ManagedPoliciesStackName}-UserFolderAccess
    Condition: ConfigureSamlRoles
  ManagersRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Managers
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/${SamlProviderName}
            Action:
              - sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSSupportAccess
        - !ImportValue
          Fn::Sub: ${ManagedPoliciesStackName}-UserSelfManagementAccess
        - !ImportValue
          Fn::Sub: ${ManagedPoliciesStackName}-UserFolderAccess
    Condition: ConfigureSamlRoles
  UsersRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Users
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/${SamlProviderName}
            Action:
              - sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - !ImportValue
          Fn::Sub: ${ManagedPoliciesStackName}-UserSelfManagementAccess
        - !ImportValue
          Fn::Sub: ${ManagedPoliciesStackName}-UserFolderAccess
    Condition: ConfigureSamlRoles
  ManagedInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ManagedInstance
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonSSMDirectoryServiceAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
Outputs:
  AdministratorsRole:
    Description: The AdministratorsRole Name
    Value: !Ref AdministratorsRole
    Export:
      Name: !Sub ${AWS::StackName}-AdministratorsRole
    Condition: ConfigureSamlRoles
  NetworkAdministratorsRole:
    Description: The NetworkAdministratorsRole Name
    Value: !Ref NetworkAdministratorsRole
    Export:
      Name: !Sub ${AWS::StackName}-NetworkAdministratorsRole
    Condition: ConfigureSamlRoles
  SystemAdministratorsRole:
    Description: The SystemAdministratorsRole Name
    Value: !Ref SystemAdministratorsRole
    Export:
      Name: !Sub ${AWS::StackName}-SystemAdministratorsRole
    Condition: ConfigureSamlRoles
  DatabaseAdministratorsRole:
    Description: The DatabaseAdministratorsRole Name
    Value: !Ref DatabaseAdministratorsRole
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseAdministratorsRole
    Condition: ConfigureSamlRoles
  SecurityAdministratorsRole:
    Description: The SecurityAdministratorsRole Name
    Value: !Ref SecurityAdministratorsRole
    Export:
      Name: !Sub ${AWS::StackName}-SecurityAdministratorsRole
    Condition: ConfigureSamlRoles
  DevelopersRole:
    Description: The DevelopersRole Name
    Value: !Ref DevelopersRole
    Export:
      Name: !Sub ${AWS::StackName}-DevelopersRole
    Condition: ConfigureSamlRoles
  ManagersRole:
    Description: The ManagersRole Name
    Value: !Ref ManagersRole
    Export:
      Name: !Sub ${AWS::StackName}-ManagersRole
    Condition: ConfigureSamlRoles
  UsersRole:
    Description: The UsersRole Name
    Value: !Ref UsersRole
    Export:
      Name: !Sub ${AWS::StackName}-UsersRole
    Condition: ConfigureSamlRoles
  ManagedInstanceRole:
    Description: The ManagedInstanceRole Name
    Value: !Ref ManagedInstanceRole
    Export:
      Name: !Sub ${AWS::StackName}-ManagedInstanceRole
