AWSTemplateFormatVersion: 2010-09-09
Description: TagFunctions Template.
  This creates Lambda Functions related to Tagging Resources.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - LayersStackName
          - BucketsStackName
          - TopicsStackName
      - Label:
          default: Function Configuration
        Parameters:
          - VpcDefaultResourceTaggerFunctionS3Key
          - VpcDefaultResourceTaggerLogRetention
    ParameterLabels:
      LayersStackName:
        default: Layers Stack Name
      BucketsStackName:
        default: Buckets Stack Name
      TopicsStackName:
        default: Topics Stack Name
      VpcDefaultResourceTaggerFunctionS3Key:
        default: VpcDefaultResourceTagger Function S3 Key
      VpcDefaultResourceTaggerLogRetention:
        default: VpcDefaultResourceTagger Log Retention
Parameters:
  LayersStackName:
    Description: Name of the CloudFormation Stack containing Layers
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Layers
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  BucketsStackName:
    Description: Name of the CloudFormation Stack containing Buckets
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Buckets
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  TopicsStackName:
    Description: Name of the CloudFormation Stack containing Topics
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: Topics
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  VpcDefaultResourceTaggerFunctionS3Key:
    Description: Key of Object within the S3 Bucket containing the VpcDefaultResourceTagger Lambda Function zipfile
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: VpcDefaultResourceTagger.zip
    AllowedPattern: ^VpcDefaultResourceTagger(/[0-9a-f]{32})?\.zip$
    ConstraintDescription: must be VpcDefaultResourceTagger.zip, or VpcDefaultResourceTagger/<md5_hash>.zip.
  VpcDefaultResourceTaggerLogRetention:
    Description: Number of days to retain CloudWatch Log Events for the VpcDefaultResourceTagger Lambda Function
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
    ConstraintDescription: must be 1, 3, 5, 7, 14, 30, 60 or 90.
Resources:
  VpcDefaultResourceTaggerRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TagVpcDefaultResourcesPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeRouteTables
                  - ec2:DescribeNetworkAcls
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeTags
                  - ec2:CreateTags
                Resource: '*'
  VpcDefaultResourceTaggerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/VpcDefaultResourceTagger
      RetentionInDays: !Ref VpcDefaultResourceTaggerLogRetention
  VpcDefaultResourceTaggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: VpcDefaultResourceTagger
      Description: A Lambda function that tags the default resources created along with a VPC, which are otherwise untagged.
      Role: !GetAtt VpcDefaultResourceTaggerRole.Arn
      Runtime: nodejs12.x
      Timeout: 30
      Layers:
        - !ImportValue
            Fn::Sub: ${LayersStackName}-AsyncCustomResourceLayerVersionArn
      Handler: VpcDefaultResourceTagger.handler
      Code:
        S3Bucket: !ImportValue
          Fn::Sub: ${BucketsStackName}-FunctionsBucket
        S3Key: !Ref VpcDefaultResourceTaggerFunctionS3Key
    DependsOn: VpcDefaultResourceTaggerLogGroup
Outputs:
  VpcDefaultResourceTaggerFunctionArn:
    Description: The VpcDefaultResourceTagger Lambda Function ARN
    Value: !GetAtt VpcDefaultResourceTaggerFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-VpcDefaultResourceTaggerFunctionArn
